config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.find(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="banner">
  <p>Simple Airbnb</p>
  <p><%= link_to "Add a flat", new_flat_path %></p>
</div>

<div class="container">
  <div class="general-info">
    <h2>All our flats</h2>
    <p>All 3 flats.</p>
  </div>

  <div class="flats">
    <% @flats.each do |flat| %>
      <div class="flat">
        <div class="flat-image" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div>
        <div class="flat-content">
          <h3><%= flat.name %></h3>
          <p><%= flat.description %></p>
          <div class="flex">
            <p class="guests"><%= flat.price_per_night %></p>
            <p class="nights"><%= flat.number_of_guests %></p>
          </div>
        </div>
        <div class="flat-actions">
          <p>More info</p>
          <p>Edit</p>
          <p>Remove</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :number_of_guests %>
  <%= f.number_field :number_of_guests %>
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<div class="banner">
  <p>Simple Airbnb</p>
  <p><%= link_to "Add a flat", new_flat_path %></p>
</div>

<div class="container">
  <div class="col-8">
    <div class="main-info"></div>
    <div class="description"></div>
  </div>
  <div class="col-4"></div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>